<?xml version="1.0"?>

<robot name="taurob_tracker"
    xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <property name="flipper_offset_x" value="0.205" />
    <property name="flipper_offset_y" value="0.15" />
    <property name="flipper_offset_z" value="0.099" />
    
    <property name="M_PI" value="3.14159" />
    <property name="angle_deg" value="45" />
    
    <xacro:include filename="$(find taurob_tracker_description)/urdf/tracker_chassis.urdf.xacro.xml" />
   
    <tracker_chassis_macro />
    
    <!--Examples of adding additional robot parts below--> 
    <xacro:include filename="$(find taurob_arm_description)/urdf/taurob_arm_collision_geoms_simple.urdf.xacro.xml" />
    <xacro:include filename="$(find taurob_arm_description)/urdf/taurob_arm.urdf.xacro.xml" />
    
    <xacro:taurob_arm_macro parent="base_link">
      <origin xyz="0.12 0 0.185" rpy="0 0 ${M_PI/2}"/>
    </xacro:taurob_arm_macro >
    
    <!--<xacro:include filename="$(find hector_xacro_tools)/urdf/sensor_macros.urdf.xacro"/>-->
    <xacro:include filename="$(find hector_sensors_description)/urdf/thermaleye_camera.urdf.xacro"/>
    <xacro:include filename="$(find hector_sensors_description)/urdf/flir_a35_camera.urdf.xacro"/>
    <xacro:include filename="$(find hector_sensors_description)/urdf/realsense_camera.urdf.xacro"/>
    <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" />
    
    <xacro:include filename="$(find hector_components_description)/urdf/vision_box_common.gazebo.xacro" />
    <xacro:include filename="$(find hector_components_description)/urdf/vision_box_common_dimensions.urdf.xacro" />
    <xacro:include filename="$(find hector_components_description)/urdf/vision_box_dimensions_hector2.urdf.xacro" />
    
    <joint name="camera/z" type="revolute">
      <origin xyz="${0.05} -0.08 0.05" rpy="0 0 ${M_PI*-0.5}"/>
      <parent link="arm_link_3"/>
      <child link="cameraYawServo"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-M_PI*3/4}" upper="${M_PI*3/4}" effort="100" velocity="100"/>
    </joint>
    
    <link name="cameraYawServo">
      <xacro:inertial_sphere mass="0.1" diameter="0.07"/>
      <visual>
        <origin xyz="0.0 0.0 ${cameraYawServo_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${cameraYawServo_size_x} ${cameraYawServo_size_y} ${cameraYawServo_size_z}"/>
        </geometry>
        <material name="Blue"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${cameraYawServo_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${cameraYawServo_size_x} ${cameraYawServo_size_y} ${cameraYawServo_size_z}"/>
        </geometry>
      </collision>
    </link>
    
    <joint name="camera/y" type="revolute">
      <origin xyz="0 0 ${cameraYawServo_size_z}" rpy="0 0 0"/>
      <parent link="cameraYawServo"/>
      <child link="mounting_link"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="100"/>
    </joint>
    <link name="mounting_link">
      <xacro:inertial_sphere mass="0.05" diameter="0.07"/>
    </link>
    
    <xacro:include filename="$(find hector_xacro_tools)/urdf/joint_macros.urdf.xacro" />
    <xacro:joint_standard_transmission name="camera/z"/>
    <xacro:joint_standard_transmission name="camera/y"/>
    
    <xacro:flir_a35_camera_model name="infrared" parent="mounting_link">
      <origin xyz="${infrared_x_position} ${infrared_y_position} ${infrared_z_position}" rpy="0 0 0"/>
    </xacro:flir_a35_camera_model>
    
    <xacro:realsense_camera_model name="openni" parent="mounting_link">
      <origin xyz="${kinect_x_position} ${kinect_y_position}  ${0.035}" rpy="${kinect_roll_position} ${kinect_pitch_position} ${kinect_yaw_position}"/>
    </xacro:realsense_camera_model>
    
    
    
    <xacro:hokuyo_utm30lx name="laser1" parent="base_link" ros_topic="laser1/scan" update_rate="40" ray_count="1081" min_angle="135" max_angle="-135">
      <origin xyz="${-0.2} 0.1 ${0.5}" rpy="0 0 0"/>
    </xacro:hokuyo_utm30lx>
    
<!--    <xacro:vision_box_common_gazebo_plugins/>   -->
    
    <xacro:include filename="$(find hector_tracker_description)/urdf/tracker_spinning_lidar_mount.urdf.xacro.xml" />
    
    <xacro:tracker_spinning_lidar_mount_macro parent="base_link"  name="spin_lidar" scaling="0.001">
      <origin xyz="-0.3 0.1 0.55" rpy="0.0 ${-M_PI*0.5} 0.0"/>
      <origin xyz="0 0.0 0.0" rpy="0.0 ${M_PI*0.25} 0.0"/>
    </xacro:tracker_spinning_lidar_mount_macro>
    
    <!--
    <xacro:include filename="$(find hector_components_description)/urdf/spinning_hokuyo_utm30lx.urdf.xacro" />
     
    <spinning_hokuyo_utm30lx_lidar_mount_offset_macro parent="chassis_link" name="front" angle_deg="34">
      <origin xyz="0.0 0 0.0" rpy="0 ${45 * M_PI/180.0} 0"/>
    </spinning_hokuyo_utm30lx_lidar_mount_offset_macro >   
    -->
</robot>
